### ISSUE TITLE
什么时候可以支持CBC模式加密解密？

### ISSUE THREAD

**Issue by ldsxp** [cforth/CryptoApp#1]
如题，没想到我是第一个提出问题的人

**Comment by cforth** [comment]
你好，CBC模式已经在[CFCryptoX](https://github.com/cforth/CryptoFactory/blob/master/CryptoFactory/CFCryptoX.py)中实现了，但目前还没有加入到CryptoApp中。因为要改动的东西太多了，还在测试中。
